spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/projectmgmt?allowPublicKeyRetrieval=true&useSSL=FALSE
        username: root
        password: root
        hikari:
            initialization-fail-timeout: 0        
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update

   # hibernate.dialect.storage_engine = innodb